version: '3.8'

services:

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB


  win-fake-cards-service:
    build:
      context: .
      dockerfile: win-fake-service.dockerfile
    restart: always
    ports:
      - "8083:8083"
